import React, { createContext, useState, useContext, useEffect } from 'react';

// Define the available languages and their string resources
export const translations = {
    ar: {
        dashboardTitle: 'لوحة التحكم - منصة السودان للجودة',
        logout: 'تسجيل الخروج',
        progressSummary: 'ملخص التقدم',
        availableUnits: 'الوحدات المتاحة',
        earnedCertificates: 'الشهادات المكتسبة',
        startStudy: 'ابدأ الدراسة',
        backToDashboard: '← العودة للوحة التحكم',
        congrats: 'مبروك! لقد نجحت في الاختبار بدرجة',
        failed: 'لم تنجح في الاختبار. درجتك:',
        tryAgain: 'حاول مرة أخرى.',
        gmpDesc: 'التصنيع الجيد',
        glpDesc: 'المختبر الجيد',
        isoDesc: 'المعايير الدولية',
        ichDesc: 'التوحيد الدولي',
        unit1: 'الوحدة الأولى',
        unit2: 'الوحدة الثانية',
        unit3: 'الوحدة الثالثة',
        unit4: 'الوحدة الرابعة',
        unit5: 'الوحدة الخامسة',
        unit6: 'الوحدة السادسة',
        unit7: 'الوحدة السابعة',
        unit8: 'الوحدة الثامنة',
        unit9: 'الوحدة التاسعة',
        unit10: 'الوحدة العاشرة',
        introGMP: 'مقدمة في GMP',
        glpBasics: 'مبادئ GLP',
        iso17025: 'معايير ISO 17025',
        ichGuidelines: 'إرشادات ICH',
        valQual: 'التحقق وصلاحية الأداء',
        dataIntegrity: 'سلامة ونزاهة البيانات',
        qrmBasics: 'إدارة مخاظر الجودة',
        gdpBasics: 'ممارسات التوزيع الجيدة GDP',
        ichQ10: 'نظام الجودة الصيدلاني ICH Q10',
        annex1: 'التصنيع المعقم (Annex 1)',
        gmpCert: 'شهادة GMP',
        earned: 'مكتسبة',
        completed: 'مكتمل',
        loading: 'جاري التحميل...',
        finish: 'إنهاء',
        score: 'النتيجة',
        question: 'السؤال',
        of: 'من',
        correctAnswerInfo: 'الإجابة الصحيحة كانت',
        lectureTitle: 'المادة العلمية للوحدة',
        proceedToQuiz: 'الانتقال إلى الاختبار',
        errorLoading: 'حدث خطأ في تحميل الأسئلة من الخادم. تم تفعيل وضع العرض التجريبي (Demo Mode).',
        courseCurriculum: 'منهج الدورة',
        back: 'رجوع',
        arnProgress: 'تقدم الدلائل',
        totalScore: 'الدرجة الكلية',
        certTitle: 'شهادة التميز المهني',
        certIntro: 'نشهد بأن السيد/السيدة:',
        certDesc: 'قد استوفى بنجاح كافة المتطلبات الشاملة وأظهر الكفاءة المهنية في البرنامج التدريبي المتقدم لإدارة الجودة الدوائية، والذي يشمل معايير الـ GMP، GLP، ISO 17025، وإرشادات الـ ICH وفقاً لمتطلبات منظمة الصحة العالمية وتميزنا في مجال الجودة الدوائية الشاملة.',
        lockedMsg: 'الشهادة مقفلة: أكمل جميع الوحدات بنسبة 90% أو أكثر لفك القفل.',
        viewCert: 'عرض الشهادة',
        printCert: 'طباعة الشهادة',
        scoreLabel: 'الدرجة',
        dateLabel: 'تاريخ الإصدار',
        gmp_intro: 'مقدمة في الجودة GMP',
        glp_basics: 'أساسيات المختبر GLP',
        iso_17025: 'كفاءة المختبرات ISO',
        ich_guidelines: 'إرشادات الـ ICH',
        validation_qualification: 'التحقق والتأهيل',
        data_integrity: 'نزاهة البيانات',
        qrm_basics: 'إدارة المخاطر QRM',
        gdp_basics: 'ممارسات التوزيع GDP',
        ich_q10: 'نظام الجودة ICH Q10',
        sterile_annex1: 'التصنيع المعقم Annex 1',
        issuingAuthority: 'منصة السودان للجودة',
        developerName: 'د. داود تاج الدين أحمد عبد الكريم',
        developerTitle: 'خبير GMP, GLP, ISO والتحقق من الجودة',
        microBadge: 'وسام الإنجاز المصغر',
        badgeId: 'معرف الوسام',
        developerProfile: 'الملف الشخصي للمطور والمؤسس',
        pledgeTitle: 'ميثاق نزاهة البيانات والالتزام المهني',
        pledgeText: 'أقر أنا المتدرب بالالتزام التام بمعايير نزاهة البيانات (ALCOA++)، وأتعهد بأداء هذا التدريب بنفسي وبالأمانة العلمية المطلوبة، مع الحفاظ على سرية المواد التعليمية وعدم تسريب أسئلة الامتحانات وفق متطلبات WHO و GMP.',
        pledgeAgree: 'أوافق وأتعهد بالالتزام',
        lectureLocked: 'المحاضرة قيد المتابعة',
        viewAllSlides: 'يجب استعراض كافة الشرائح لفتح الاختبار',
        auditLog: 'سجل التدقيق الرقمي',
        eventLogin: 'تسجيل دخول',
        eventQuiz: 'بدء اختبار',
        eventCert: 'استخراج شهادة',
        eventPledge: 'توقيع الميثاق',
        sampleCert: 'نموذج الشهادة المشجع',
        surveyTitle: 'تقييم فعالية التدريب (ICH Q10)',
        surveyQ1: 'هل غطت المادة العلمية احتياجاتك المعرفية؟',
        surveyQ2: 'كيف تقيم مستوى سهولة استخدام المنصة؟',
        surveyQ3: 'هل تشعر بزيادة كفاءتك بعد هذا التدريب؟',
        submitSurvey: 'إرسال التقييم واستلام الشهادة',
        quizTitle: 'اختبار الكفاءة المهنية',
        loadingQuestions: 'جاري تحميل الأسئلة الفنية...',
        submitExam: 'تسليم الامتحان',
        next: 'التالي',
        true: 'صح',
        false: 'خطأ',
        placeholderFill: 'اكتب إجابتك هنا...',
        logicHint: 'المنطق العلمي',
        retakeBtn: 'إعادة الاختبار للنجاح (90%)',
        scoreLowWarning: 'درجتك الحالية لا تؤهلك للحصول على الشهادة. يرجى المذاكرة وإعادة المحاولة.',
        darkMode: 'الوضع الليلي',
        lightMode: 'الوضع النهاري',
        toolkit: 'أدوات الجودة',
        academy: 'الأكاديمية',
        fmeaTitle: 'محلل المخاطر (FMEA)',
        severity: 'الشدة (S)',
        occurrence: 'التكرار (O)',
        detectability: 'القدرة على الكشف (D)',
        calculateRPN: 'حساب رقم أولوية المخاطر (RPN)',
        riskLevel: 'مستوى المخاطر',
        lowRisk: 'منخفض',
        medRisk: 'متوسط',
        highRisk: 'عالي',
        criticalRisk: 'حرج',
        batchSim: 'محاكاة التوقيع الإلكتروني',
        signerName: 'اسم الموقع',
        signReason: 'سبب التوقيع',
        confirmSign: 'تأكيد التوقيع (E-Sign)',
        auditTrail: 'سجل التدقيق (Audit Trail)',
        batchRecords: 'سجلات التشغيل (Batch Records)',
        nmpbReg: 'الرقابة الدوائية (NMPB)',
        level: 'المستوى',
        xp: 'نقاط الخبرة (XP)',
        xpRange: 'النقاط للمستوى التالي',
        leaderboard: 'لوحة الصدارة',
        rank: 'الترتيب',
        student: 'المتدرب',
        perfectScoreBadge: 'وسام الدرجة الكاملة',
        sudanExpertBadge: 'وسام خبير السودان',
        speedLearnerBadge: 'وسام المتعلم السريع',
        nmpbReg: 'الرقابة الدوائية (NMPB)',
        unit13: 'الوحدة الثالثة عشر',
    },
    en: {
        // ... same structure for English
        dashboardTitle: 'Dashboard - Sudan Quality Platform',
        logout: 'Logout',
        progressSummary: 'Progress Summary',
        availableUnits: 'Available Units',
        earnedCertificates: 'Earned Certificates',
        startStudy: 'Start Study',
        backToDashboard: '← Back to Dashboard',
        congrats: 'Congratulations! You passed the test with a score of',
        failed: 'You did not pass the test. Your score:',
        tryAgain: 'Try again.',
        gmpDesc: 'Good Manufacturing',
        glpDesc: 'Good Laboratory',
        isoDesc: 'International Standards',
        ichDesc: 'Intl Harmonization',
        unit1: 'Unit 1',
        unit2: 'Unit 2',
        unit3: 'Unit 3',
        unit4: 'Unit 4',
        unit5: 'Unit 5',
        unit6: 'Unit 6',
        unit7: 'Unit 7',
        unit8: 'Unit 8',
        unit9: 'Unit 9',
        unit10: 'Unit 10',
        introGMP: 'Introduction to GMP',
        glpBasics: 'GLP Basics',
        iso17025: 'ISO 17025 Standards',
        ichGuidelines: 'ICH Guidelines',
        valQual: 'Validation & Qualification',
        dataIntegrity: 'Data Integrity (ALCOA+)',
        qrmBasics: 'Quality Risk Management',
        gdpBasics: 'Good Distribution Practices GDP',
        ichQ10: 'ICH Q10 Quality System',
        annex1: 'Sterile Manufacturing (Annex 1)',
        issuingAuthority: 'Sudan Quality Platform',
        developerName: 'Dr. Daoud Tajeldeinn Ahmed Abdelkarim',
        developerTitle: 'GMP, GLP, ISO & Quality Specialist',
        microBadge: 'Micro-credential Badge',
        badgeId: 'Badge ID',
        developerProfile: 'Developer & Founder Profile',
        certTitle: 'Certificate of Professional Excellence',
        certIntro: 'This is to certify that:',
        certDesc: 'Has successfully fulfilled the comprehensive requirements and demonstrated professional proficiency in the Advanced Pharmaceutical Quality Management Program, encompassing WHO GMP, GLP, ISO 17025, and ICH Guidelines, with excellence in Comprehensive Pharmaceutical Quality.',
        pledgeTitle: 'Data Integrity & Professional Pledge',
        pledgeText: 'I hereby pledge to strictly adhere to Data Integrity standards (ALCOA++), promising to perform this training personally and with the required scientific honesty, maintaining the confidentiality of materials and exams as per WHO and GMP requirements.',
        pledgeAgree: 'I Agree and Pledge',
        lectureLocked: 'Lecture in Progress',
        viewAllSlides: 'You must view all slides to unlock the exam',
        auditLog: 'Digital Audit Trail',
        eventLogin: 'Login',
        eventQuiz: 'Started Quiz',
        eventCert: 'Generated Certificate',
        eventPledge: 'Signed Pledge',
        sampleCert: 'Sample Certificate (Encouragement)',
        surveyTitle: 'Effectiveness Assessment (ICH Q10)',
        surveyQ1: 'Did the materials cover your knowledge needs?',
        surveyQ2: 'How do you rate the platform usability?',
        surveyQ3: 'Do you feel a competency increase after this training?',
        submitSurvey: 'Submit Survey & Get Certificate',
        gmp_intro: 'GMP Introduction',
        glp_basics: 'GLP Basics',
        iso_17025: 'ISO 17025 Competence',
        ich_guidelines: 'ICH Guidelines',
        validation_qualification: 'Validation & Qualification',
        data_integrity: 'Data Integrity',
        qrm_basics: 'Quality Risk Management (QRM)',
        gdp_basics: 'Good Distribution Practices (GDP)',
        ich_q10: 'ICH Q10 Quality System',
        sterile_annex1: 'Sterile Manufacturing (Annex 1)',
        totalScore: 'Total Score',
        quizTitle: 'Professional Competency Exam',
        loadingQuestions: 'Loading technical questions...',
        submitExam: 'Submit Exam',
        next: 'Next',
        true: 'True',
        false: 'False',
        placeholderFill: 'Type your answer here...',
        logicHint: 'Technical Logic',
        retakeBtn: 'Retake Exam to Pass (90%)',
        scoreLowWarning: 'Your current score is below the passing threshold. Please review and try again.',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        toolkit: 'Toolkit',
        academy: 'Academy',
        fmeaTitle: 'FMEA Risk Analyzer',
        severity: 'Severity (S)',
        occurrence: 'Occurrence (O)',
        detectability: 'Detectability (D)',
        calculateRPN: 'Calculate RPN',
        riskLevel: 'Risk Level',
        lowRisk: 'Low',
        medRisk: 'Medium',
        highRisk: 'High',
        criticalRisk: 'Critical',
        batchSim: 'E-Signature Simulation',
        signerName: 'Signer Name',
        signReason: 'Reason for Signing',
        confirmSign: 'Confirm E-Sign',
        auditTrail: 'Audit Trail',
        batchRecords: 'Batch Records & Records',
        nmpbReg: 'NMPB Regulatory',
        level: 'Level',
        xp: 'Experience Points (XP)',
        xpRange: 'XP till Next Level',
        leaderboard: 'Leaderboard',
        rank: 'Rank',
        student: 'Student',
        perfectScoreBadge: 'Perfect Score Badge',
        sudanExpertBadge: 'Sudan Expert Badge',
        speedLearnerBadge: 'Speed Learner Badge',
        nmpbReg: 'NMPB Regulatory',
        unit13: 'Unit 13',
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    // Try to get language from local storage, default to Arabic
    const [language, setLanguage] = useState(() => {
        const savedLang = localStorage.getItem('appLanguage');
        return savedLang || 'ar';
    });

    const toggleLanguage = () => {
        setLanguage(prevLang => prevLang === 'ar' ? 'en' : 'ar');
    };

    const t = (key) => {
        return translations[language][key] || key;
    };

    // Add Theme state
    const [theme, setTheme] = useState(() => {
        const savedTheme = localStorage.getItem('appTheme');
        return savedTheme || 'light';
    });

    useEffect(() => {
        localStorage.setItem('appTheme', theme);
        document.documentElement.setAttribute('data-theme', theme);
    }, [theme]);

    const toggleTheme = () => {
        setTheme(prev => prev === 'light' ? 'dark' : 'light');
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t, theme, toggleTheme }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
