const fs = require('fs');
const path = require('path');

const contentPath = path.join(__dirname, '../src/data/content_new.js');
let content = fs.readFileSync(contentPath, 'utf8');

const processValidationUnit = `
    'process-validation': {
      title: { ar: 'التحقق من العمليات', en: 'Process Validation' },
      slides: [
        { id: 'pv_s1', type: 'learning', regulatoryRef: { code: 'FDA Guidance 2011', body: 'FDA' }, ar: { title: 'مفهوم التحقق من العمليات الحديث', text: 'لم يعد التحقق من العملية مجرد "إنتاج 3 دفعات ناجحة متتالية". بل هو "جمع وتقييم البيانات من مرحلة تصميم العملية وحتى الإنتاج التجاري، لتوفير دليل علمي على أن العملية قادرة باستمرار على تقديم منتج عالي الجودة".' }, en: { title: 'Modern Process Validation Concept', text: 'Process Validation is no longer just "3 successful consecutive batches". It is the "collection and evaluation of data, from the process design stage through commercial production, which establishes scientific evidence that a process is capable of consistently delivering quality product".' } },
        { id: 'pv_s2', type: 'learning', ar: { title: 'المرحلة 1: تصميم العملية (Process Design)', text: 'تبدأ في قسم البحث والتطوير (R&D).\\nالهدف: بناء عملية تعتمد على فهم علمي قوي (QbD - Quality by Design).\\nفي هذه المرحلة يتم تحديد:\\n- CQAs (سمات الجودة الحرجة للمنتج).\\n- CPPs (محددات العملية الحرجة التي تؤثر على الجودة).' }, en: { title: 'Stage 1: Process Design', text: 'Starts in Research & Development (R&D).\\nGoal: Build a process based on strong scientific understanding (QbD).\\nIn this stage we identify:\\n- CQAs (Critical Quality Attributes).\\n- CPPs (Critical Process Parameters).' } },
        { id: 'pv_s3', type: 'learning', ar: { title: 'المتغيرات الحرجة (CMA, CPP, CQA)', text: 'CMA (Critical Material Attributes): خصائص المواد الخام (مثل حجم الحبيبات).\\nCPP (Critical Process Parameters): متغيرات التشغيل (مثل وقت الخلط، سرعة الدوران).\\nCQA (Critical Quality Attributes): خصائص المنتج النهائي (مثل الذوبان، الصلابة).\\n\\nالقاعدة: نتحكم في CMA و CPP لضمان الحصول على CQA.' }, en: { title: 'Critical Variables (CMA, CPP, CQA)', text: 'CMA (Critical Material Attributes): Raw material properties (e.g., particle size).\\nCPP (Critical Process Parameters): Operating variables (e.g., mixing time, speed).\\nCQA (Critical Quality Attributes): Final product properties (e.g., dissolution, hardness).\\n\\nRule: We control CMAs and CPPs to guarantee the CQA.' } },
        { id: 'pv_s4', type: 'learning', regulatoryRef: { code: 'EMA Annex 15', body: 'EMA' }, ar: { title: 'المرحلة 2: تأهيل العملية (Process Qualification)', text: 'هذه هي المرحلة التقليدية التي تُثبت قدرة التصميم على أرض الواقع التجاري.\\nتتكون من خطوتين:\\n1. تأهيل المرافق والمعدات (Equipment Qualification).\\n2. التحقق من أداء العملية (PPQ - Process Performance Qualification)، وهي غالبًا ما تعادل الـ 3 دفعات التجريبية الناجحة.' }, en: { title: 'Stage 2: Process Qualification', text: 'This is the traditional stage that proves the design in actual commercial scale.\\nConsists of two steps:\\n1. Facilities and Equipment Qualification.\\n2. Process Performance Qualification (PPQ), which typically equates to the 3 successful commercial-scale batches.' } },
        { id: 'pv_s5', type: 'learning', ar: { title: 'المرحلة 3: التحقق المستمر (CPV)', text: 'التحقق المستمر (Continued Process Verification - CPV) يضمن بقاء العملية تحت السيطرة أثناء الإنتاج الروتيني.\\n\\nلا يكفي النجاح في PPQ، بل يجب تحليل بيانات الإنتاج المستمرة (استخدام إحصاءات SPC مثل مخططات التحكم Control Charts) لاكتشاف أي انحراف مبكر (Trends).' }, en: { title: 'Stage 3: Continued Process Verification (CPV)', text: 'CPV ensures the process remains in a state of control during routine commercial production.\\n\\nSuccess in PPQ is not enough; routine production data must be analyzed (using SPC tools like Control Charts) to detect early trends.' } },
        { id: 'pv_s6', type: 'casestudy', regulatoryRef: { code: 'FDA 483', body: 'FDA' }, ar: { title: 'دراسة حالة: إهمال المرحلة الثالثة (CPV)', text: 'شركة أدوية اكتفت بـ 3 دفعات تحقق ناجحة (Stage 2) وأوقفت المراقبة الإحصائية.\\nبعد 6 أشهر، ظهرت دفعات فاشلة بسبب تغير غير ملحوظ في رطوبة المصنع.\\nملاحظة FDA: "الشركة فشلت في تنفيذ برنامج التحقق المستمر (Stage 3) لرصد التغيرات الدقيقة في العملية".' }, en: { title: 'Case Study: Neglecting CPV', text: 'A company relied solely on 3 successful PPQ batches (Stage 2) and stopped statistical monitoring.\\nAfter 6 months, batches failed due to a subtle shift in facility humidity.\\nFDA Observation: "The firm failed to establish an ongoing program to collect and analyze product and process data (Stage 3)."' } },
        { id: 'pv_discussion', type: 'discussion', ar: { title: 'نقاش: كم عدد الدفعات في الـ PPQ؟', text: 'قديماً كان الرقم السحري دائماً "3 دفعات". حالياً تقول التوجيهات الحديثة أن العدد يجب أن يُبرر علمياً. ما هي العوامل التي قد تجعلنا نحتاج 5 دفعات تحقق بدلاً من 3؟' }, en: { title: 'Discussion: How many PPQ batches?', text: 'Historically, the magic number was always "3 batches". Modern guidelines state the number must be scientifically justified. What factors might require 5 validation batches instead of 3?' } }
      ],
      examQuestionPool: ['pv_q1', 'pv_q2', 'pv_q3', 'pv_q4', 'pv_q5', 'pv_q6', 'pv_tf1', 'pv_tf2']
    },`;

const holdTimeUnit = `
    'hold-time-stability': {
      title: { ar: 'دراسات فترة الاحتفاظ', en: 'Hold Time Studies' },
      slides: [
        { id: 'ht_s1', type: 'learning', regulatoryRef: { code: 'WHO TRS 992', body: 'WHO' }, ar: { title: 'ما هي دراسة فترة الاحتفاظ (Hold Time Study)؟', text: 'هي دراسة تثبت استقرار جودة المواد الوسيطة (Intermediates) والمنتج السائب (Bulk) أثناء فترات التوقف قبل استكمال خطوات الإنتاج أو التعبئة النهائية.\\nمثل: بقاء الخليط السائب في المستودع لعدة أيام قبل تعبئته في كبسولات.' }, en: { title: 'What is a Hold Time Study?', text: 'A study that establishes the stability of intermediate and bulk products during holding periods before completing manufacturing or final packaging.\\nExample: Storing a bulk blend in the warehouse for days before encapsulation.' } },
        { id: 'ht_s2', type: 'learning', ar: { title: 'المخاطر الرئيسية أثناء فترة الاحتفاظ', text: '1. التدهور الكيميائي (Chemical Degradation): أكسدة، تحلل مائي.\\n2. التلوث الميكروبي (Microbial Contamination): نمو البكتيريا، خاصة في المحاليل والكريمات.\\n3. التغيرات الفيزيائية (Physical Changes): ترسب المعلقات، انفصال المستحلبات، امتصاص الرطوبة.' }, en: { title: 'Major Risks During Hold Times', text: '1. Chemical Degradation: Oxidation, hydrolysis.\\n2. Microbial Contamination: Bacterial growth, especially in liquids and creams.\\n3. Physical Changes: Suspension settling, emulsion cracking, moisture absorption.' } },
        { id: 'ht_s3', type: 'learning', ar: { title: 'كيف تُجرى دراسة الـ Hold Time؟', text: 'تؤخذ عينات من المنتج السائب المعبأ في نفس ظروف/عبوات المستودع الحقيقية (أو نموذج مصغر). وتُختبر في فترات زمنية متزايدة (مثلاً: يوم 0، يوم 15، يوم 30).\\nيجب أن تبقى جميع معايير الجودة مطابقة للمواصفات طوال الفترة المحددة.' }, en: { title: 'How is a Hold Time Study Conducted?', text: 'Samples are taken from the bulk product stored in the exact real-world warehouse conditions/containers (or a scaled-down representative). They are tested at increasing intervals (e.g., day 0, day 15, day 30).\\nAll quality attributes must remain within specification throughout the hold period.' } },
        { id: 'ht_s4', type: 'casestudy', ar: { title: 'دراسة حالة: التلوث الميكروبي للمياه', text: 'مصنع قام بتحضير معلق شراب (Syrup) وتركه في تانك الخلط 4 أيام بسبب عطل في ماكينة التعبئة. عند التحليل الميكروبي، ظهر نمو بكتيري يفوق الحد المسموح.\\nالخطأ: الحد الأقصى المعتمد للاحتفاظ (Validated Hold Time) كان 48 ساعة فقط.' }, en: { title: 'Case Study: Microbial Contamination', text: 'A manufacturer formulated a syrup suspension and left it in the mixing tank for 4 days due to a filling machine breakdown. Microbial testing revealed out-of-spec bacterial growth.\\nThe Error: The Validated Hold Time was only 48 hours.' } },
        { id: 'ht_discussion', type: 'discussion', ar: { title: 'نقاش: حاويات التخزين الوسيط', text: 'هل يجب إجراء دراسة الـ Hold Time في أكياس بلاستيكية عادية أم يجب استخدام نفس مادة الأكياس (PE bags) وحاويات (IBCs) المستخدمة فعلياً في الإنتاج؟ ولماذا؟' }, en: { title: 'Discussion: Intermediate Storage Containers', text: 'Should a Hold Time study be conducted using standard plastic bags, or must it use the exact material (e.g., PE bags) and containers (IBCs) actually used in production? Why?' } }
      ],
      examQuestionPool: ['ht_q1', 'ht_q2', 'ht_q3', 'ht_tf1']
    }`;

const questions = `
    'pv_q1': { type: 'mcq', difficulty: 'easy', questionText: { ar: 'وفقاً للمفهوم الحديث، التحقق من العملية (Process Validation) يتكون من كم مرحلة أساسية؟', en: 'According to modern concepts, Process Validation consists of how many main stages?' }, options: { ar: ['مرحلة واحدة', 'مرحلتين', 'ثلاث مراحل', 'خمس مراحل'], en: ['One stage', 'Two stages', 'Three stages', 'Five stages'] }, correctAnswer: 2 },
    'pv_q2': { type: 'mcq', difficulty: 'medium', questionText: { ar: 'ما المقصود بـ CQA؟', en: 'What does CQA stand for?' }, options: { ar: ['Control Quality Audit', 'Critical Quality Attribute', 'Continuous Quality Assessment', 'Critical Quantity Approval'], en: ['Control Quality Audit', 'Critical Quality Attribute', 'Continuous Quality Assessment', 'Critical Quantity Approval'] }, correctAnswer: 1 },
    'pv_q3': { type: 'mcq', difficulty: 'medium', questionText: { ar: 'في أي مرحلة من مراحل التحقق من العملية يتم استخدام التحليل الإحصائي المستمر (مثل Control Charts)؟', en: 'In which stage of Process Validation is continuous statistical analysis (like Control Charts) used?' }, options: { ar: ['المرحلة 1: Process Design', 'المرحلة 2: Process Qualification', 'المرحلة 3: Continued Process Verification (CPV)', 'في مرحلة الأبحاث الأولية فقط'], en: ['Stage 1: Process Design', 'Stage 2: Process Qualification', 'Stage 3: Continued Process Verification (CPV)', 'Only in preliminary research phase'] }, correctAnswer: 2 },
    'pv_q4': { type: 'mcq', difficulty: 'medium', questionText: { ar: 'المتغيرات التشغيلية التي يتم التحكم بها لضمان جودة المنتج النهائي تُسمى:', en: 'The operational variables controlled to ensure final product quality are called:' }, options: { ar: ['CQAs', 'CPPs', 'CMAs', 'SOPs'], en: ['CQAs', 'CPPs', 'CMAs', 'SOPs'] }, correctAnswer: 1 },
    'pv_q5': { type: 'mcq', difficulty: 'easy', questionText: { ar: 'المرحلة الثانية (Stage 2) من التحقق من العملية تتضمن عادةً إجراء الدفعات التجريبية الناجحة (PPQ)، كم عددها تقليدياً؟', en: 'Stage 2 of Process Validation typically involves successful commercial batches (PPQ), traditionally how many?' }, options: { ar: ['دفعة واحدة', 'دفعتين', '3 دفعات', '10 دفعات'], en: ['1 batch', '2 batches', '3 batches', '10 batches'] }, correctAnswer: 2 },
    'pv_q6': { type: 'mcq', difficulty: 'hard', questionText: { ar: 'ما العلاقة بين CPP و CQA؟', en: 'What is the relationship between CPP and CQA?' }, options: { ar: ['لا توجد علاقة بينهما', 'التحكم في CPP يضمن تحقيق الـ CQA المطلوبة للمنتج', 'الـ CQA هي متغيرات الماكينة والـ CPP هي خصائص المنتج', 'كلاهما يُقاس فقط في المختبرات ولا علاقة لهما بالإنتاج'], en: ['There is no relationship', 'Controlling the CPP ensures achieving the desired CQA for the product', 'CQA are machine variables and CPP are product attributes', 'Both are only measured in labs and have no relation to production'] }, correctAnswer: 1 },
    'pv_tf1': { type: 'tf', difficulty: 'easy', questionText: { ar: 'بمجرد نجاح 3 دفعات في مرحلة الـ PPQ، لا حاجة لمراقبة أداء العملية بعد ذلك.', en: 'Once 3 PPQ batches pass successfully, there is no need to monitor process performance afterward.' }, correctAnswer: false },
    'pv_tf2': { type: 'tf', difficulty: 'medium', questionText: { ar: 'سمك القرص الدوائي وصلابته تعتبر أمثلة على سمات الجودة الحرجة (CQAs).', en: 'Tablet thickness and hardness are considered examples of Critical Quality Attributes (CQAs).' }, correctAnswer: true },

    'ht_q1': { type: 'mcq', difficulty: 'easy', questionText: { ar: 'الهدف الأساسي من دراسة الـ Hold Time هو:', en: 'The main goal of a Hold Time study is to:' }, options: { ar: ['إطالة عمر الآلات', 'إثبات استقرار جودة المواد الوسيطة أثناء فترات التخزين المؤقتة', 'تقليل عدد الموظفين المطلوبين', 'تسريع عملية التعبئة'], en: ['Prolong machine life', 'Establish the stability of intermediate quality during temporary storage periods', 'Reduce staff required', 'Speed up packaging process'] }, correctAnswer: 1 },
    'ht_q2': { type: 'mcq', difficulty: 'medium', questionText: { ar: 'أي من الأشكال الصيدلانية التالية يعتبر الأكثر عرضة للخطر الميكروبي أثناء فترة الاحتفاظ؟', en: 'Which of the following dosage forms is most vulnerable to microbial risk during hold times?' }, options: { ar: ['الأقراص المضغوطة الجافة', 'المحاليل المائية والمعلقات', 'الكبسولات الجيلاتينية الصلبة', 'المساحيق الجافة'], en: ['Dry compressed tablets', 'Aqueous solutions and suspensions', 'Hard gelatin capsules', 'Dry powders'] }, correctAnswer: 1 },
    'ht_q3': { type: 'mcq', difficulty: 'medium', questionText: { ar: 'حاويات التخزين المستخدمة في دراسة الـ Hold Time يجب أن تكون:', en: 'The storage containers used in a Hold Time study must be:' }, options: { ar: ['أرخص الحاويات المتاحة', 'مصنوعة من الزجاج الشفاف دائماً', 'ممثلة تماماً لحاويات التخزين الحقيقية المستخدمة في الإنتاج', 'مختلفة عن الحاويات الفعلية لإضافة التحدي'], en: ['Cheapest available', 'Always made of clear glass', 'Fully representative of the actual storage containers used in production', 'Different from actual containers to add challenge'] }, correctAnswer: 2 },
    'ht_tf1': { type: 'tf', difficulty: 'easy', questionText: { ar: 'فترة الاحتفاظ (Hold Time) لا تؤثر مطلقاً على التركيب الكيميائي للدواء.', en: 'Hold Time has absolutely no impact on the chemical composition of the drug.' }, correctAnswer: false },
`;

// 1. Insert the units
const endOfUnitsSearch = /'mv_fill1'\]\s*\}\s*\},\s*allQuestions:\s*\{/g;
if (endOfUnitsSearch.test(content)) {
    content = content.replace(endOfUnitsSearch, \`'mv_fill1']
    },
\${processValidationUnit}
\${holdTimeUnit}
  },
  allQuestions: {\`);
}

// 2. Insert the questions
const allQuestionsSearch = /allQuestions:\s*\{/g;
content = content.replace(allQuestionsSearch, \`allQuestions: {
\${questions}\`);

fs.writeFileSync(contentPath, content, 'utf8');
console.log("Phase 3 applied successfully.");
