const fs = require('fs');
const path = require('path');

const contentPath = path.join(__dirname, '../src/data/content_new.js');
let content = fs.readFileSync(contentPath, 'utf8');

// 1. Remove the duplicate 'cleaning-validation' unit at the end of units
// It looks like:
//     'cleaning-validation': {
//       slides: [ ... ],
//       examQuestionPool: ['cv_q1', 'cv_q2', 'cv_q3', 'cv_q4', 'cv_q5', 'cv_tf1', 'cv_tf2', 'cv_fill1']
//     }
//   },
//   allQuestions: {

const duplicatePattern = /'cleaning-validation':\s*\{\s*slides:\s*\[[\s\S]*?examQuestionPool:\s*\[[^\]]+\]\s*\}\s*\},/g;
if (content.match(duplicatePattern)) {
    content = content.replace(duplicatePattern, '},');
    console.log("Removed duplicate cleaning-validation.");
} else {
    // try to match the exact string from lines 358-369
    const backupPattern = /'cleaning-validation':\s*\{\s*slides:\s*\[[\s\S]*?'cv_fill1'\]\s*\}/g;
    content = content.replace(backupPattern, '');
    content = content.replace(/,\s*\},/g, '},'); // cleanup trailing comma
    console.log("Attempted manual removal of duplicate.");
}

// 2. Add 'method-validation' unit
const methodValidationUnit = `
    'method-validation': {
      title: { ar: 'التحقق من طرق التحليل', en: 'Analytical Method Validation' },
      slides: [
        { id: 'mv_s1', type: 'learning', regulatoryRef: { code: 'ICH Q2(R2)', body: 'ICH' }, ar: { title: 'مقدمة في التحقق من الطرق التحليلية', text: 'التحقق من طرق التحليل هو عملية التقييم الموثقة التي تثبت أن الطريقة التحليلية مناسبة للغرض المقصود منها.\\n\\nهذا يضمن موثوقية وثبات النتائج المخبرية (مثل قوة الدواء والشوائب) في كل مرة يتم فيها الاختبار.' }, en: { title: 'Introduction to Method Validation', text: 'Method Validation is the documented evaluation process proving that an analytical method is suitable for its intended purpose.\\n\\nThis ensures the reliability and consistency of laboratory results (e.g., assay, impurities) every time the test is run.' } },
        { id: 'mv_s2', type: 'learning', regulatoryRef: { code: 'ICH Q2(R2)', body: 'ICH' }, ar: { title: 'متى يجب التحقق من الطريقة؟', text: 'يجب إجراء التحقق في الحالات التالية:\\n1. تطوير طريقة تحليلية جديدة.\\n2. تعديل طريقة تحليلية قائمة (مثل تغيير نوع عمود الـ HPLC).\\n3. استخدام طريقة دستور أدوية (Pharmacopeial method) في مختبر جديد أو لمنتج جديد (وهنا يُسمى التحقق: Method Verification).' }, en: { title: 'When is Validation Required?', text: 'Validation must be performed when:\\n1. Developing a new analytical method.\\n2. Modifying an existing method (e.g., changing HPLC column type).\\n3. Using a pharmacopeial method in a new lab or for a new product (this is termed: Method Verification).' } },
        { id: 'mv_s3', type: 'learning', ar: { title: '1. التحديد (Specificity / Selectivity)', text: 'التحديد هو قدرة الطريقة التحليلية على قياس المادة الفعالة بدقة وبشكل لا لبس فيه، حتى في وجود مكونات أخرى (مثل السواغات، الشوائب، ومنتجات التحلل).\\n\\nتُثبت عن طريق مقارنة قمة الدواء (Peak) بقمم المواد الأخرى لضمان عدم وجود تداخل (Interference).' }, en: { title: '1. Specificity / Selectivity', text: 'Specificity is the ability to assess unequivocally the analyte in the presence of components which may be expected to be present (excipients, impurities, degradants).\\n\\nProven by comparing the drug peak against other peaks to ensure no interference occurs.' } },
        { id: 'mv_s4', type: 'learning', ar: { title: '2. الدقة وصحة النتائج (Accuracy)', text: 'صحة النتائج (Accuracy) تعبر عن مدى تقارب القيمة المقاسة من القيمة الحقيقية أو المرجعية.\\n\\nتُقاس عبر اختبار الاسترداد (Recovery Testing): إضافة كمية معروفة من المادة الفعالة إلى عينة وهمية (Placebo) وحساب نسبة الاسترداد (عادة 98-102% للمواد الفعالة).' }, en: { title: '2. Accuracy', text: 'Accuracy expresses the closeness of agreement between the value which is accepted either as a conventional true value or an accepted reference value and the value found.\\n\\nMeasured via Recovery Testing: Spiking a known amount of active ingredient into a placebo and calculating recovery % (typically 98-102% for assays).' } },
        { id: 'mv_s5', type: 'learning', ar: { title: '3. الدقة الإجرائية (Precision)', text: 'تعبر عن درجة التوافق بين سلسلة من القياسات لعينة متجانسة.\\nوتقسم لثلاثة مستويات:\\n1. التكرارية (Repeatability): نفس المحلل، نفس الجهاز، نفس اليوم.\\n2. الدقة المتوسطة (Intermediate Precision): نفس المختبر، لكن محللين مختلفين، أو أيام مختلفة.\\n3. الاستنساخية (Reproducibility): بين مختبرات مختلفة (للتوحيد القياسي).' }, en: { title: '3. Precision', text: 'Expresses the degree of agreement among individual test results when the procedure is applied repeatedly to multiple samplings.\\nThree levels:\\n1. Repeatability: Same analyst, same equipment, same day.\\n2. Intermediate Precision: Same lab, different analysts or days.\\n3. Reproducibility: Between different laboratories (standardization).' } },
        { id: 'mv_s6', type: 'learning', ar: { title: '4. الخطية (Linearity)', text: 'قدرة الطريقة التحليلية (ضمن نطاق محدد) على إعطاء نتائج تتناسب طردياً مع تركيز المادة الفعالة في العينة.\\n\\nتُقاس بتحضير 5 تراكيز مختلفة على الأقل، ورسم العلاقة لحساب معامل الارتباط (Correlation Coefficient R²). يجب أن يكون R² قريباً من 1 (مثلاً > 0.999).' }, en: { title: '4. Linearity', text: 'The ability of the method (within a given range) to obtain test results which are directly proportional to the concentration of analyte in the sample.\\n\\nMeasured using at least 5 concentrations, plotting the curve, and calculating the Correlation Coefficient (R²). R² should be close to 1 (e.g., > 0.999).' } },
        { id: 'mv_s7', type: 'learning', ar: { title: '5. المدى (Range)', text: 'المدى هو المسافة بين الحد الأعلى والحد الأدنى للتركيز الذي أثبتت الطريقة التحليلية عندها أنها تتمتع بمستوى مناسب من التحديد، الدقة، والخطية.\\n\\nيُشتق المدى عادة من دراسة الخطية ويعتمد على الغرض من الطريقة (مثلاً 80% إلى 120% لاختبار قوة الدواء).' }, en: { title: '5. Range', text: 'The interval between the upper and lower concentration of analyte in the sample for which it has been demonstrated that the analytical procedure has a suitable level of precision, accuracy, and linearity.\\n\\nUsually derived from linearity studies and depends on the method purpose (e.g., 80% to 120% for assay).' } },
        { id: 'mv_s8', type: 'learning', ar: { title: '6. حد الكشف و التحديد الكمي (LOD & LOQ)', text: 'حد الكشف (LOD): أقل كمية من المادة يمكن الكشف عنها، لكن ليس بالضرورة قياسها بدقة.\\nحد التحديد الكمي (LOQ): أقل كمية من المادة يمكن قياسها كمياً بدقة عالية.\\n\\nيُستخدمان بكثرة في طرق اختبار الشوائب (Impurities) أو بقايا التنظيف (Cleaning Residues) ولا يُطلب إثباتهما لاختبارات قوة الدواء (Assay).' }, en: { title: '6. LOD & LOQ', text: 'Limit of Detection (LOD): The lowest amount of analyte which can be detected but not necessarily quantitated as an exact value.\\nLimit of Quantitation (LOQ): The lowest amount of analyte which can be quantitatively determined with suitable precision and accuracy.\\n\\nMainly used for Impurities or Cleaning Residues, not for Assays.' } },
        { id: 'mv_s9', type: 'learning', ar: { title: '7. المتانة (Robustness)', text: 'المتانة هي قدرة الطريقة التحليلية على البقاء غير متأثرة بالتغيرات الصغيرة المتعمدة في معايير الطريقة.\\n\\nأمثلة على التغيرات (في الـ HPLC):\\n- تغيير درجة حرارة العمود (± 2°C).\\n- تغيير معدل التدفق (± 0.1 mL/min).\\n- تغيير نسبة الطور المتحرك (Mobile Phase pH).\\nيثبت أن الطريقة موثوقة في ظروف العمل الطبيعية المتغيرة.' }, en: { title: '7. Robustness', text: 'Robustness is a measure of the capacity of an analytical procedure to remain unaffected by small, but deliberate variations in method parameters.\\n\\nExamples in HPLC:\\n- Column temperature (± 2°C).\\n- Flow rate (± 0.1 mL/min).\\n- Mobile Phase pH variations.\\nProves reliability during normal usage.' } },
        { id: 'mv_s10', type: 'casestudy', regulatoryRef: { code: 'FDA Warning Letter', body: 'FDA' }, ar: { title: 'دراسة حالة: فشل التحقق في استقرار المحلول', text: 'أثناء تفتيش، لاحظ المفتش أن المحللين يحضرون عينات الـ HPLC يوم الخميس ويتركونها في جهاز الـ Autosampler طوال عطلة نهاية الأسبوع للحقن الآلي.\\n\\nالمشكلة: طريقة التحقق لم تتضمن دراسة "ثبات المحلول" (Solution Stability) لأكثر من 12 ساعة. المحاليل كانت تتحلل بمرور الوقت معطية نتائج خاطئة (Out of Specification).\\n\\nالدرس: يجب تحقق ثبات المحاليل القياسية والعينات ضمن فترة الاستخدام.' }, en: { title: 'Case Study: Solution Stability Failure', text: 'During an inspection, it was noted that analysts prepared HPLC samples on Thursday and left them in the autosampler over the weekend for automated injection.\\n\\nIssue: Method validation lacked a "Solution Stability" study beyond 12 hours. Solutions degraded over time yielding Out of Specification (OOS) results.\\n\\nLesson: Stability of standard and sample solutions must be validated for their intended use period.' } },
        { id: 'mv_discussion', type: 'discussion', ar: { title: 'نقاش: التحقق من طرق الدستور', text: 'إذا قررت شركتك استخدام طريقة تحليلية مذكورة بالكامل في دستور الأدوية البريطاني (BP)، هل تحتاج الشركة لعمل Method Validation كامل، أم Method Verification؟ وما الفرق بينهما؟' }, en: { title: 'Discussion: Pharmacopeial Methods', text: 'If your company uses a method fully described in the British Pharmacopoeia (BP), does it require full Method Validation or just Method Verification? What is the difference?' } }
      ],
      examQuestionPool: ['mv_q1', 'mv_q2', 'mv_q3', 'mv_q4', 'mv_q5', 'mv_q6', 'mv_q7', 'mv_q8', 'mv_q9', 'mv_q10', 'mv_tf1', 'mv_tf2', 'mv_tf3', 'mv_fill1']
    },`;

// Find where to insert the new unit. We will insert it just before 'cleaning-validation' or 'nmpb-reg'
if (content.includes("'nmpb-reg': {")) {
    content = content.replace("'nmpb-reg': {", methodValidationUnit + "\\n    'nmpb-reg': {");
} else {
    console.error("Could not find nmpb-reg to insert method-validation unit.");
}

// 3. Add method-validation questions
const methodValidationQuestions = `
    'mv_q1': { type: 'mcq', difficulty: 'easy', questionText: { ar: 'ما هو الهدف الأساسي من التحقق من الطريقة التحليلية؟', en: 'What is the primary goal of Analytical Method Validation?' }, options: { ar: ['تسريع عملية التحليل المخبري', 'إثبات أن الطريقة التحليلية مناسبة وموثوقة للغرض المقصود منها', 'تقليل تكلفة استهلاك المواد الكيميائية', 'الاستغناء عن أجهزة التحليل القديمة'], en: ['Speed up the laboratory analysis process', 'Prove the analytical method is suitable and reliable for its intended purpose', 'Reduce the cost of chemical consumption', 'Eliminate the need for old analytical equipment'] }, correctAnswer: 1 },
    'mv_q2': { type: 'mcq', difficulty: 'medium', questionText: { ar: 'أي من المعلمات التالية تقيس قدرة الطريقة التحليلية على إعطاء نتائج تتناسب طردياً مع تركيز المادة الفعالة؟', en: 'Which parameter measures the ability of the analytical method to give results directly proportional to the analyte concentration?' }, options: { ar: ['الخطية (Linearity)', 'الدقة (Accuracy)', 'التحديد (Specificity)', 'المتانة (Robustness)'], en: ['Linearity', 'Accuracy', 'Specificity', 'Robustness'] }, correctAnswer: 0 },
    'mv_q3': { type: 'mcq', difficulty: 'medium', questionText: { ar: 'ما هو الفرق بين LOD و LOQ؟', en: 'What is the difference between LOD and LOQ?' }, options: { ar: ['لا يوجد فرق بينهما', 'LOD هو أقل كمية يمكن كشفها، بينما LOQ هي أقل كمية يمكن قياسها كمياً بدقة', 'LOD يستخدم للشوائب، و LOQ يستخدم للأسواغات', 'LOD هو الحد الأقصى و LOQ هو الحد الأدنى'], en: ['There is no difference', 'LOD is the lowest amount that can be detected, while LOQ is the lowest amount that can be quantitated accurately', 'LOD is used for impurities, LOQ for excipients', 'LOD is the maximum limit and LOQ is the minimum'] }, correctAnswer: 1 },
    'mv_q4': { type: 'mcq', difficulty: 'easy', questionText: { ar: 'أي مما يلي يُعبر عن الدقة المتوسطة (Intermediate Precision)؟', en: 'Which of the following expresses Intermediate Precision?' }, options: { ar: ['نفس المحلل ونفس الجهاز في نفس اليوم', 'تحليل العينة في مختبرين في بلدين مختلفين', 'محللون مختلفون في نفس المختبر وفي أيام مختلفة', 'عدم وجود أي تداخل بين الشوائب'], en: ['Same analyst and equipment on same day', 'Analysis in two labs in different countries', 'Different analysts in the same lab on different days', 'No interference between impurities'] }, correctAnswer: 2 },
    'mv_q5': { type: 'mcq', difficulty: 'medium', questionText: { ar: 'كيف يتم قياس صحة النتائج (Accuracy) عادةً؟', en: 'How is Accuracy typically measured?' }, options: { ar: ['عن طريق تغيير درجة حرارة عمود الـ HPLC', 'عن طريق حساب معامل الارتباط للخطية', 'من خلال اختبار الاسترداد (Recovery Testing) بإضافة تركيز معروف', 'من خلال فحص العينة بالعين المجردة'], en: ['By changing HPLC column temperature', 'By calculating linearity correlation coefficient', 'Through Recovery Testing by spiking a known concentration', 'By visually inspecting the sample'] }, correctAnswer: 2 },
    'mv_q6': { type: 'mcq', difficulty: 'easy', questionText: { ar: 'المتانة (Robustness) تقيم الطريقة التحليلية عند حدوث:', en: 'Robustness evaluates the analytical method upon occurrence of:' }, options: { ar: ['تغيرات كبيرة وجوهرية في الطريقة', 'تغيرات صغيرة متعمدة في معايير الطريقة مثل درجة الحرارة والتدفق', 'تغير في اسم المادة الفعالة', 'تغير في نوع الجهاز من HPLC إلى GC'], en: ['Major and fundamental changes to the method', 'Small, deliberate variations in method parameters like temperature and flow', 'Change in active ingredient name', 'Change in equipment type from HPLC to GC'] }, correctAnswer: 1 },
    'mv_q7': { type: 'mcq', difficulty: 'hard', questionText: { ar: 'هل اختبار (Assay) لقوة الدواء يتطلب إثباتاً لـ LOD و LOQ؟', en: 'Does an Assay test for drug strength require establishing LOD and LOQ?' }, options: { ar: ['نعم، دائماً', 'لا، يتم إثباتهما فقط لاختبارات الشوائب والبقايا', 'نعم، لكن LOD فقط', 'نعم، للمستحضرات الصلبة فقط'], en: ['Yes, always', 'No, they are established only for impurity and residue testing', 'Yes, but LOD only', 'Yes, for solid dosage forms only'] }, correctAnswer: 1 },
    'mv_q8': { type: 'mcq', difficulty: 'medium', questionText: { ar: 'ماذا يسمى الإجراء المتبع عند استخدام مختبرلطريقة تحليلية موجودة مسبقاً في دستور الأدوية (Pharmacopeia)؟', en: 'What is the procedure called when a lab uses a pre-existing Pharmacopeial analytical method?' }, options: { ar: ['Method Validation (تحقق كامل)', 'Method Verification (إثبات المطابقة)', 'Method Transfer (نقل الطريقة)', 'Method Validation Protocol'], en: ['Method Validation', 'Method Verification', 'Method Transfer', 'Method Validation Protocol'] }, correctAnswer: 1 },
    'mv_q9': { type: 'mcq', difficulty: 'medium', questionText: { ar: 'أي معامل يؤكد "التحديد" (Specificity) لطريقة الـ HPLC؟', en: 'Which parameter confirms "Specificity" of an HPLC method?' }, options: { ar: ['انفصال قمة الدواء بوضوح عن قمم الشوائب (Resolution)', 'الحصول على نسبة استرداد 100%', 'تكرار الحقن 6 مرات بنجاح', 'تغير الـ pH بدون تأثير على النتائج'], en: ['Clear separation (Resolution) of drug peak from impurity peaks', 'Achieving 100% recovery', 'Repeating injection 6 times successfully', 'Changing pH without affecting results'] }, correctAnswer: 0 },
    'mv_q10': { type: 'mcq', difficulty: 'medium', questionText: { ar: 'ماذا يحدث إذا تجاهلت الشركة دراسة "ثبات المحلول" (Solution Stability)؟', en: 'What happens if a company ignores the "Solution Stability" study?' }, options: { ar: ['تحصل على تقييم إيجابي من المفتش', 'قد تتحلل العينة أو القياسي بمرور الوقت معطية نتائج خاطئة (OOS)', 'يصبح التحليل أسرع وأقل تكلفة', 'تزداد الخطية (Linearity) بشكل تلقائي'], en: ['Receives positive feedback from inspector', 'Sample or standard may degrade over time yielding OOS results', 'Analysis becomes faster and cheaper', 'Linearity automatically increases'] }, correctAnswer: 1 },
    'mv_tf1': { type: 'tf', difficulty: 'easy', questionText: { ar: 'التحقق من طرق التحليل (Method Validation) إلزامي فقط للأدوية الجديدة وغير مطلوب للأدوية الجنيسة (Generics).', en: 'Method Validation is mandatory only for new drugs and not required for generics.' }, correctAnswer: false },
    'mv_tf2': { type: 'tf', difficulty: 'medium', questionText: { ar: 'التكرارية (Repeatability) تعني الحصول على نفس النتائج عند استخدام نفس المحلل لنفس الجهاز في نفس اليوم.', en: 'Repeatability means obtaining the same results when the same analyst uses the same equipment on the same day.' }, correctAnswer: true },
    'mv_tf3': { type: 'tf', difficulty: 'easy', questionText: { ar: 'طريقة التحليل الموصوفة بالكامل في دستور الأدوية لا تحتاج إلى أي شكل من أشكال التقييم عند تطبيقها في المختبر.', en: 'A fully described pharmacopeial analytical method requires no form of evaluation when implemented in a lab.' }, correctAnswer: false },
    'mv_fill1': { type: 'fill', difficulty: 'medium', questionText: { ar: 'أقل كمية من المادة يمكن قياسها كمياً بدقة عالية تُسمى حد التحديد الـ ___ (LOQ).', en: 'The lowest amount of analyte which can be quantitatively determined with suitable accuracy is called Limit of ___ (LOQ).' }, correctAnswer: { ar: 'الكمي', en: 'Quantitation' } },
`;

// Insert questions at the beginning of allQuestions
if (content.includes("allQuestions: {")) {
    content = content.replace("allQuestions: {", "allQuestions: {\\n" + methodValidationQuestions);
} else {
    console.error("Could not find allQuestions to insert questions.");
}

fs.writeFileSync(contentPath, content, 'utf8');
console.log("Updated content_new.js successfully!");
